/**
 * CountryAlphaConverter - Country code conversions (ISO 3166)
 * 
 * Fully compatible with the C# Utils/CountryAlphaConverter.cs.
 * Converts between ISO 3166 Alpha-2 and Alpha-3 country codes.
 */

interface CountryInfo {
  Alpha2: string;
  Alpha3: string;
  Name: string;
}

const COUNTRIES: CountryInfo[] = [
  { Alpha2: 'AF', Alpha3: 'AFG', Name: 'Afghanistan' },
  { Alpha2: 'AL', Alpha3: 'ALB', Name: 'Albania' },
  { Alpha2: 'DZ', Alpha3: 'DZA', Name: 'Algeria' },
  { Alpha2: 'AS', Alpha3: 'ASM', Name: 'American Samoa' },
  { Alpha2: 'AD', Alpha3: 'AND', Name: 'Andorra' },
  { Alpha2: 'AO', Alpha3: 'AGO', Name: 'Angola' },
  { Alpha2: 'AI', Alpha3: 'AIA', Name: 'Anguilla' },
  { Alpha2: 'AQ', Alpha3: 'ATA', Name: 'Antarctica' },
  { Alpha2: 'AG', Alpha3: 'ATG', Name: 'Antigua and Barbuda' },
  { Alpha2: 'AR', Alpha3: 'ARG', Name: 'Argentina' },
  { Alpha2: 'AM', Alpha3: 'ARM', Name: 'Armenia' },
  { Alpha2: 'AW', Alpha3: 'ABW', Name: 'Aruba' },
  { Alpha2: 'AU', Alpha3: 'AUS', Name: 'Australia' },
  { Alpha2: 'AT', Alpha3: 'AUT', Name: 'Austria' },
  { Alpha2: 'AZ', Alpha3: 'AZE', Name: 'Azerbaijan' },
  { Alpha2: 'BS', Alpha3: 'BHS', Name: 'Bahamas' },
  { Alpha2: 'BH', Alpha3: 'BHR', Name: 'Bahrain' },
  { Alpha2: 'BD', Alpha3: 'BGD', Name: 'Bangladesh' },
  { Alpha2: 'BB', Alpha3: 'BRB', Name: 'Barbados' },
  { Alpha2: 'BY', Alpha3: 'BLR', Name: 'Belarus' },
  { Alpha2: 'BE', Alpha3: 'BEL', Name: 'Belgium' },
  { Alpha2: 'BZ', Alpha3: 'BLZ', Name: 'Belize' },
  { Alpha2: 'BJ', Alpha3: 'BEN', Name: 'Benin' },
  { Alpha2: 'BM', Alpha3: 'BMU', Name: 'Bermuda' },
  { Alpha2: 'BT', Alpha3: 'BTN', Name: 'Bhutan' },
  { Alpha2: 'BO', Alpha3: 'BOL', Name: 'Bolivia' },
  { Alpha2: 'BA', Alpha3: 'BIH', Name: 'Bosnia and Herzegovina' },
  { Alpha2: 'BW', Alpha3: 'BWA', Name: 'Botswana' },
  { Alpha2: 'BR', Alpha3: 'BRA', Name: 'Brazil' },
  { Alpha2: 'IO', Alpha3: 'IOT', Name: 'British Indian Ocean Territory' },
  { Alpha2: 'VG', Alpha3: 'VGB', Name: 'British Virgin Islands' },
  { Alpha2: 'BN', Alpha3: 'BRN', Name: 'Brunei' },
  { Alpha2: 'BG', Alpha3: 'BGR', Name: 'Bulgaria' },
  { Alpha2: 'BF', Alpha3: 'BFA', Name: 'Burkina Faso' },
  { Alpha2: 'BI', Alpha3: 'BDI', Name: 'Burundi' },
  { Alpha2: 'KH', Alpha3: 'KHM', Name: 'Cambodia' },
  { Alpha2: 'CM', Alpha3: 'CMR', Name: 'Cameroon' },
  { Alpha2: 'CA', Alpha3: 'CAN', Name: 'Canada' },
  { Alpha2: 'CV', Alpha3: 'CPV', Name: 'Cape Verde' },
  { Alpha2: 'KY', Alpha3: 'CYM', Name: 'Cayman Islands' },
  { Alpha2: 'CF', Alpha3: 'CAF', Name: 'Central African Republic' },
  { Alpha2: 'TD', Alpha3: 'TCD', Name: 'Chad' },
  { Alpha2: 'CL', Alpha3: 'CHL', Name: 'Chile' },
  { Alpha2: 'CN', Alpha3: 'CHN', Name: 'China' },
  { Alpha2: 'CX', Alpha3: 'CXR', Name: 'Christmas Island' },
  { Alpha2: 'CC', Alpha3: 'CCK', Name: 'Cocos Islands' },
  { Alpha2: 'CO', Alpha3: 'COL', Name: 'Colombia' },
  { Alpha2: 'KM', Alpha3: 'COM', Name: 'Comoros' },
  { Alpha2: 'CK', Alpha3: 'COK', Name: 'Cook Islands' },
  { Alpha2: 'CR', Alpha3: 'CRI', Name: 'Costa Rica' },
  { Alpha2: 'HR', Alpha3: 'HRV', Name: 'Croatia' },
  { Alpha2: 'CU', Alpha3: 'CUB', Name: 'Cuba' },
  { Alpha2: 'CW', Alpha3: 'CUW', Name: 'Curacao' },
  { Alpha2: 'CY', Alpha3: 'CYP', Name: 'Cyprus' },
  { Alpha2: 'CZ', Alpha3: 'CZE', Name: 'Czech Republic' },
  { Alpha2: 'CD', Alpha3: 'COD', Name: 'Democratic Republic of the Congo' },
  { Alpha2: 'DK', Alpha3: 'DNK', Name: 'Denmark' },
  { Alpha2: 'DJ', Alpha3: 'DJI', Name: 'Djibouti' },
  { Alpha2: 'DM', Alpha3: 'DMA', Name: 'Dominica' },
  { Alpha2: 'DO', Alpha3: 'DOM', Name: 'Dominican Republic' },
  { Alpha2: 'TL', Alpha3: 'TLS', Name: 'East Timor' },
  { Alpha2: 'EC', Alpha3: 'ECU', Name: 'Ecuador' },
  { Alpha2: 'EG', Alpha3: 'EGY', Name: 'Egypt' },
  { Alpha2: 'SV', Alpha3: 'SLV', Name: 'El Salvador' },
  { Alpha2: 'GQ', Alpha3: 'GNQ', Name: 'Equatorial Guinea' },
  { Alpha2: 'ER', Alpha3: 'ERI', Name: 'Eritrea' },
  { Alpha2: 'EE', Alpha3: 'EST', Name: 'Estonia' },
  { Alpha2: 'ET', Alpha3: 'ETH', Name: 'Ethiopia' },
  { Alpha2: 'FK', Alpha3: 'FLK', Name: 'Falkland Islands' },
  { Alpha2: 'FO', Alpha3: 'FRO', Name: 'Faroe Islands' },
  { Alpha2: 'FJ', Alpha3: 'FJI', Name: 'Fiji' },
  { Alpha2: 'FI', Alpha3: 'FIN', Name: 'Finland' },
  { Alpha2: 'FR', Alpha3: 'FRA', Name: 'France' },
  { Alpha2: 'PF', Alpha3: 'PYF', Name: 'French Polynesia' },
  { Alpha2: 'GA', Alpha3: 'GAB', Name: 'Gabon' },
  { Alpha2: 'GM', Alpha3: 'GMB', Name: 'Gambia' },
  { Alpha2: 'GE', Alpha3: 'GEO', Name: 'Georgia' },
  { Alpha2: 'DE', Alpha3: 'DEU', Name: 'Germany' },
  { Alpha2: 'GH', Alpha3: 'GHA', Name: 'Ghana' },
  { Alpha2: 'GI', Alpha3: 'GIB', Name: 'Gibraltar' },
  { Alpha2: 'GR', Alpha3: 'GRC', Name: 'Greece' },
  { Alpha2: 'GL', Alpha3: 'GRL', Name: 'Greenland' },
  { Alpha2: 'GD', Alpha3: 'GRD', Name: 'Grenada' },
  { Alpha2: 'GU', Alpha3: 'GUM', Name: 'Guam' },
  { Alpha2: 'GT', Alpha3: 'GTM', Name: 'Guatemala' },
  { Alpha2: 'GG', Alpha3: 'GGY', Name: 'Guernsey' },
  { Alpha2: 'GN', Alpha3: 'GIN', Name: 'Guinea' },
  { Alpha2: 'GW', Alpha3: 'GNB', Name: 'Guinea-Bissau' },
  { Alpha2: 'GY', Alpha3: 'GUY', Name: 'Guyana' },
  { Alpha2: 'HT', Alpha3: 'HTI', Name: 'Haiti' },
  { Alpha2: 'HN', Alpha3: 'HND', Name: 'Honduras' },
  { Alpha2: 'HK', Alpha3: 'HKG', Name: 'Hong Kong' },
  { Alpha2: 'HU', Alpha3: 'HUN', Name: 'Hungary' },
  { Alpha2: 'IS', Alpha3: 'ISL', Name: 'Iceland' },
  { Alpha2: 'IN', Alpha3: 'IND', Name: 'India' },
  { Alpha2: 'ID', Alpha3: 'IDN', Name: 'Indonesia' },
  { Alpha2: 'IR', Alpha3: 'IRN', Name: 'Iran' },
  { Alpha2: 'IQ', Alpha3: 'IRQ', Name: 'Iraq' },
  { Alpha2: 'IE', Alpha3: 'IRL', Name: 'Ireland' },
  { Alpha2: 'IM', Alpha3: 'IMN', Name: 'Isle of Man' },
  { Alpha2: 'IL', Alpha3: 'ISR', Name: 'Israel' },
  { Alpha2: 'IT', Alpha3: 'ITA', Name: 'Italy' },
  { Alpha2: 'CI', Alpha3: 'CIV', Name: 'Ivory Coast' },
  { Alpha2: 'JM', Alpha3: 'JAM', Name: 'Jamaica' },
  { Alpha2: 'JP', Alpha3: 'JPN', Name: 'Japan' },
  { Alpha2: 'JE', Alpha3: 'JEY', Name: 'Jersey' },
  { Alpha2: 'JO', Alpha3: 'JOR', Name: 'Jordan' },
  { Alpha2: 'KZ', Alpha3: 'KAZ', Name: 'Kazakhstan' },
  { Alpha2: 'KE', Alpha3: 'KEN', Name: 'Kenya' },
  { Alpha2: 'KI', Alpha3: 'KIR', Name: 'Kiribati' },
  { Alpha2: 'XK', Alpha3: 'XKX', Name: 'Kosovo' },
  { Alpha2: 'KW', Alpha3: 'KWT', Name: 'Kuwait' },
  { Alpha2: 'KG', Alpha3: 'KGZ', Name: 'Kyrgyzstan' },
  { Alpha2: 'LA', Alpha3: 'LAO', Name: 'Laos' },
  { Alpha2: 'LV', Alpha3: 'LVA', Name: 'Latvia' },
  { Alpha2: 'LB', Alpha3: 'LBN', Name: 'Lebanon' },
  { Alpha2: 'LS', Alpha3: 'LSO', Name: 'Lesotho' },
  { Alpha2: 'LR', Alpha3: 'LBR', Name: 'Liberia' },
  { Alpha2: 'LY', Alpha3: 'LBY', Name: 'Libya' },
  { Alpha2: 'LI', Alpha3: 'LIE', Name: 'Liechtenstein' },
  { Alpha2: 'LT', Alpha3: 'LTU', Name: 'Lithuania' },
  { Alpha2: 'LU', Alpha3: 'LUX', Name: 'Luxembourg' },
  { Alpha2: 'MO', Alpha3: 'MAC', Name: 'Macau' },
  { Alpha2: 'MK', Alpha3: 'MKD', Name: 'Macedonia' },
  { Alpha2: 'MG', Alpha3: 'MDG', Name: 'Madagascar' },
  { Alpha2: 'MW', Alpha3: 'MWI', Name: 'Malawi' },
  { Alpha2: 'MY', Alpha3: 'MYS', Name: 'Malaysia' },
  { Alpha2: 'MV', Alpha3: 'MDV', Name: 'Maldives' },
  { Alpha2: 'ML', Alpha3: 'MLI', Name: 'Mali' },
  { Alpha2: 'MT', Alpha3: 'MLT', Name: 'Malta' },
  { Alpha2: 'MH', Alpha3: 'MHL', Name: 'Marshall Islands' },
  { Alpha2: 'MR', Alpha3: 'MRT', Name: 'Mauritania' },
  { Alpha2: 'MU', Alpha3: 'MUS', Name: 'Mauritius' },
  { Alpha2: 'YT', Alpha3: 'MYT', Name: 'Mayotte' },
  { Alpha2: 'MX', Alpha3: 'MEX', Name: 'Mexico' },
  { Alpha2: 'FM', Alpha3: 'FSM', Name: 'Micronesia' },
  { Alpha2: 'MD', Alpha3: 'MDA', Name: 'Moldova' },
  { Alpha2: 'MC', Alpha3: 'MCO', Name: 'Monaco' },
  { Alpha2: 'MN', Alpha3: 'MNG', Name: 'Mongolia' },
  { Alpha2: 'ME', Alpha3: 'MNE', Name: 'Montenegro' },
  { Alpha2: 'MS', Alpha3: 'MSR', Name: 'Montserrat' },
  { Alpha2: 'MA', Alpha3: 'MAR', Name: 'Morocco' },
  { Alpha2: 'MZ', Alpha3: 'MOZ', Name: 'Mozambique' },
  { Alpha2: 'MM', Alpha3: 'MMR', Name: 'Myanmar' },
  { Alpha2: 'NA', Alpha3: 'NAM', Name: 'Namibia' },
  { Alpha2: 'NR', Alpha3: 'NRU', Name: 'Nauru' },
  { Alpha2: 'NP', Alpha3: 'NPL', Name: 'Nepal' },
  { Alpha2: 'NL', Alpha3: 'NLD', Name: 'Netherlands' },
  { Alpha2: 'AN', Alpha3: 'ANT', Name: 'Netherlands Antilles' },
  { Alpha2: 'NC', Alpha3: 'NCL', Name: 'New Caledonia' },
  { Alpha2: 'NZ', Alpha3: 'NZL', Name: 'New Zealand' },
  { Alpha2: 'NI', Alpha3: 'NIC', Name: 'Nicaragua' },
  { Alpha2: 'NE', Alpha3: 'NER', Name: 'Niger' },
  { Alpha2: 'NG', Alpha3: 'NGA', Name: 'Nigeria' },
  { Alpha2: 'NU', Alpha3: 'NIU', Name: 'Niue' },
  { Alpha2: 'KP', Alpha3: 'PRK', Name: 'North Korea' },
  { Alpha2: 'MP', Alpha3: 'MNP', Name: 'Northern Mariana Islands' },
  { Alpha2: 'NO', Alpha3: 'NOR', Name: 'Norway' },
  { Alpha2: 'OM', Alpha3: 'OMN', Name: 'Oman' },
  { Alpha2: 'PK', Alpha3: 'PAK', Name: 'Pakistan' },
  { Alpha2: 'PW', Alpha3: 'PLW', Name: 'Palau' },
  { Alpha2: 'PS', Alpha3: 'PSE', Name: 'Palestine' },
  { Alpha2: 'PA', Alpha3: 'PAN', Name: 'Panama' },
  { Alpha2: 'PG', Alpha3: 'PNG', Name: 'Papua New Guinea' },
  { Alpha2: 'PY', Alpha3: 'PRY', Name: 'Paraguay' },
  { Alpha2: 'PE', Alpha3: 'PER', Name: 'Peru' },
  { Alpha2: 'PH', Alpha3: 'PHL', Name: 'Philippines' },
  { Alpha2: 'PN', Alpha3: 'PCN', Name: 'Pitcairn' },
  { Alpha2: 'PL', Alpha3: 'POL', Name: 'Poland' },
  { Alpha2: 'PT', Alpha3: 'PRT', Name: 'Portugal' },
  { Alpha2: 'PR', Alpha3: 'PRI', Name: 'Puerto Rico' },
  { Alpha2: 'QA', Alpha3: 'QAT', Name: 'Qatar' },
  { Alpha2: 'CG', Alpha3: 'COG', Name: 'Republic of the Congo' },
  { Alpha2: 'RE', Alpha3: 'REU', Name: 'Reunion' },
  { Alpha2: 'RO', Alpha3: 'ROU', Name: 'Romania' },
  { Alpha2: 'RU', Alpha3: 'RUS', Name: 'Russia' },
  { Alpha2: 'RW', Alpha3: 'RWA', Name: 'Rwanda' },
  { Alpha2: 'BL', Alpha3: 'BLM', Name: 'Saint Barthelemy' },
  { Alpha2: 'SH', Alpha3: 'SHN', Name: 'Saint Helena' },
  { Alpha2: 'KN', Alpha3: 'KNA', Name: 'Saint Kitts and Nevis' },
  { Alpha2: 'LC', Alpha3: 'LCA', Name: 'Saint Lucia' },
  { Alpha2: 'MF', Alpha3: 'MAF', Name: 'Saint Martin' },
  { Alpha2: 'PM', Alpha3: 'SPM', Name: 'Saint Pierre and Miquelon' },
  { Alpha2: 'VC', Alpha3: 'VCT', Name: 'Saint Vincent and the Grenadines' },
  { Alpha2: 'WS', Alpha3: 'WSM', Name: 'Samoa' },
  { Alpha2: 'SM', Alpha3: 'SMR', Name: 'San Marino' },
  { Alpha2: 'ST', Alpha3: 'STP', Name: 'Sao Tome and Principe' },
  { Alpha2: 'SA', Alpha3: 'SAU', Name: 'Saudi Arabia' },
  { Alpha2: 'SN', Alpha3: 'SEN', Name: 'Senegal' },
  { Alpha2: 'RS', Alpha3: 'SRB', Name: 'Serbia' },
  { Alpha2: 'SC', Alpha3: 'SYC', Name: 'Seychelles' },
  { Alpha2: 'SL', Alpha3: 'SLE', Name: 'Sierra Leone' },
  { Alpha2: 'SG', Alpha3: 'SGP', Name: 'Singapore' },
  { Alpha2: 'SX', Alpha3: 'SXM', Name: 'Sint Maarten' },
  { Alpha2: 'SK', Alpha3: 'SVK', Name: 'Slovakia' },
  { Alpha2: 'SI', Alpha3: 'SVN', Name: 'Slovenia' },
  { Alpha2: 'SB', Alpha3: 'SLB', Name: 'Solomon Islands' },
  { Alpha2: 'SO', Alpha3: 'SOM', Name: 'Somalia' },
  { Alpha2: 'ZA', Alpha3: 'ZAF', Name: 'South Africa' },
  { Alpha2: 'KR', Alpha3: 'KOR', Name: 'South Korea' },
  { Alpha2: 'SS', Alpha3: 'SSD', Name: 'South Sudan' },
  { Alpha2: 'ES', Alpha3: 'ESP', Name: 'Spain' },
  { Alpha2: 'LK', Alpha3: 'LKA', Name: 'Sri Lanka' },
  { Alpha2: 'SD', Alpha3: 'SDN', Name: 'Sudan' },
  { Alpha2: 'SR', Alpha3: 'SUR', Name: 'Suriname' },
  { Alpha2: 'SJ', Alpha3: 'SJM', Name: 'Svalbard and Jan Mayen' },
  { Alpha2: 'SZ', Alpha3: 'SWZ', Name: 'Swaziland' },
  { Alpha2: 'SE', Alpha3: 'SWE', Name: 'Sweden' },
  { Alpha2: 'CH', Alpha3: 'CHE', Name: 'Switzerland' },
  { Alpha2: 'SY', Alpha3: 'SYR', Name: 'Syria' },
  { Alpha2: 'TW', Alpha3: 'TWN', Name: 'Taiwan' },
  { Alpha2: 'TJ', Alpha3: 'TJK', Name: 'Tajikistan' },
  { Alpha2: 'TZ', Alpha3: 'TZA', Name: 'Tanzania' },
  { Alpha2: 'TH', Alpha3: 'THA', Name: 'Thailand' },
  { Alpha2: 'TG', Alpha3: 'TGO', Name: 'Togo' },
  { Alpha2: 'TK', Alpha3: 'TKL', Name: 'Tokelau' },
  { Alpha2: 'TO', Alpha3: 'TON', Name: 'Tonga' },
  { Alpha2: 'TT', Alpha3: 'TTO', Name: 'Trinidad and Tobago' },
  { Alpha2: 'TN', Alpha3: 'TUN', Name: 'Tunisia' },
  { Alpha2: 'TR', Alpha3: 'TUR', Name: 'Turkey' },
  { Alpha2: 'TM', Alpha3: 'TKM', Name: 'Turkmenistan' },
  { Alpha2: 'TC', Alpha3: 'TCA', Name: 'Turks and Caicos Islands' },
  { Alpha2: 'TV', Alpha3: 'TUV', Name: 'Tuvalu' },
  { Alpha2: 'VI', Alpha3: 'VIR', Name: 'U.S. Virgin Islands' },
  { Alpha2: 'UG', Alpha3: 'UGA', Name: 'Uganda' },
  { Alpha2: 'UA', Alpha3: 'UKR', Name: 'Ukraine' },
  { Alpha2: 'AE', Alpha3: 'ARE', Name: 'United Arab Emirates' },
  { Alpha2: 'GB', Alpha3: 'GBR', Name: 'United Kingdom' },
  { Alpha2: 'US', Alpha3: 'USA', Name: 'United States' },
  { Alpha2: 'UY', Alpha3: 'URY', Name: 'Uruguay' },
  { Alpha2: 'UZ', Alpha3: 'UZB', Name: 'Uzbekistan' },
  { Alpha2: 'VU', Alpha3: 'VUT', Name: 'Vanuatu' },
  { Alpha2: 'VA', Alpha3: 'VAT', Name: 'Vatican' },
  { Alpha2: 'VE', Alpha3: 'VEN', Name: 'Venezuela' },
  { Alpha2: 'VN', Alpha3: 'VNM', Name: 'Vietnam' },
  { Alpha2: 'WF', Alpha3: 'WLF', Name: 'Wallis and Futuna' },
  { Alpha2: 'EH', Alpha3: 'ESH', Name: 'Western Sahara' },
  { Alpha2: 'YE', Alpha3: 'YEM', Name: 'Yemen' },
  { Alpha2: 'ZM', Alpha3: 'ZMB', Name: 'Zambia' },
  { Alpha2: 'ZW', Alpha3: 'ZWE', Name: 'Zimbabwe' },
];

// Create lookup maps for efficient conversion
const alpha2ToCountry = new Map<string, CountryInfo>();
const alpha3ToCountry = new Map<string, CountryInfo>();

COUNTRIES.forEach((country) => {
  alpha2ToCountry.set(country.Alpha2.toUpperCase(), country);
  alpha3ToCountry.set(country.Alpha3.toUpperCase(), country);
});

/**
 * ISO3166 namespace - Country code conversion functions
 */
export const ISO3166 = {
  /**
   * Returns country info from Alpha-3 code
   * @param alpha3 - 3-letter country code (e.g., "USA")
   * @returns Country info or null
   */
  FromAlpha3: (alpha3: string): CountryInfo | null => {
    if (!alpha3) return null;
    return alpha3ToCountry.get(alpha3.toUpperCase()) || null;
  },

  /**
   * Returns country info from Alpha-2 code
   * @param alpha2 - 2-letter country code (e.g., "US")
   * @returns Country info or null
   */
  FromAlpha2: (alpha2: string): CountryInfo | null => {
    if (!alpha2) return null;
    return alpha2ToCountry.get(alpha2.toUpperCase()) || null;
  },

  /**
   * Returns the list of all countries
   */
  GetAllCountries: (): CountryInfo[] => {
    return [...COUNTRIES];
  },
};
